#Settings
title: Soft Interface
description: Where awesome design starts
email: zelek.hubert@gmail.com
logo: 'logo.svg'

bg-img: 'hero-bg.jpg'
avatar: 'travitar.jpg'

#Menu
menu:
- {name: About Me, url: '#about'}
- {name: Work, url: '#work'}
- {name: Clients, url: '#clients'}
- {name: Contact, url: '#contact'}

#Work
work:
- {name: Tech Mock-up, category: 'Photography', thumbnail: 'work-1'}
- {name: Heja stockholm!, category: 'Marketing', thumbnail: 'work-2'}
- {name: Clean UI, category: 'Web Design', thumbnail: 'work-3'}
- {name: Relistic mock-up, category: 'Print', thumbnail: 'work-4'}
- {name: Londoner, category: 'Media', thumbnail: 'work-5'}
- {name: Paper bag, category: 'Branding', thumbnail: 'work-6'}
- {name: Ceramic bottle, category: 'Branding', thumbnail: 'work-7'}
- {name: Cool shirt, category: 'Brandning', thumbnail: 'work-8'}

#Services
services:
- {name: Timing, icon: 'stopwatch', content: 'Our web design team will spend time with our digital marketing team to ensure the core principles of effective websites.'}
- {name: Presentation, icon: 'presentation', content: 'Our web design team will spend time with our digital marketing team to ensure the core principles of effective websites.'}
- {name: Accurate, icon: 'target', content: 'Our web design team will spend time with our digital marketing team to ensure the core principles of effective websites.'}
- {name: Design, icon: 'stack-exchange', content: 'Our web design team will spend time with our digital marketing team to ensure the core principles of effective websites.'}
- {name: Developer, icon: 'browser', content: 'Our web design team will spend time with our digital marketing team to ensure the core principles of effective websites.'}
- {name: Production, icon: 'tools-2', content: 'Our web design team will spend time with our digital marketing team to ensure the core principles of effective websites.'}

#Team
team:
- {name: Victoria Natalio, title: 'CEO', img: 'team-1'}
- {name: Jhon Smith, title: 'Vice President', img: 'team-2'}
- {name: Eva Snow, title: 'Marketing Team', img: 'team-3'}
- {name: Elton Blub, title: 'Accountant', img: 'team-4'}
- {name: Jin Xui Hai, title: 'Programmer', img: 'team-5'}
- {name: Steve Morrison, title: 'Programmer', img: 'team-6'}
- {name: Xiao Mi, title: 'UI Design', img: 'team-7'}
